name: daily_planner
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.35.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  

 
